version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     

    steps:
      - checkout
      - run:
          name: Build 2.1
          command: dotnet build -c "Debug 2.1"
      - run:
          name: Build 3.0
          command: dotnet build -c "Debug 3.0"
      - run:
          name: Test 2.1
          command: |
            dotnet test -c "Debug 2.1" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            mv test/coverage.opencover.xml test/coverage.opencover.2.1.xml
      - run:
          name: Test 3.0
          command: |
            dotnet test -c "Debug 3.0" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            mv test/coverage.opencover.xml test/coverage.opencover.3.0.xml
      - run:
          name: Submit coverage data
          command: '~\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover test -f coverage.opencover.*.xml -r $env:COVERALLS_REPO_TOKEN'
