version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     

    steps:
      - checkout
      - run:
          name: Setup
          command: dotnet tool install -g coveralls.net --version 1.0.0
      - run:
          name: Build 2.1
          command: dotnet build -c "Debug 2.1"
      - run:
          name: Build 3.0
          command: dotnet build -c "Debug 3.0"
      - run:
          name: Test 2.1
          command: dotnet test -c "Debug 2.1" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.2.1.xml
      - run:
          name: Test 3.0
          command: dotnet test -c "Debug 3.0" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.3.0.xml
      - run:
          name: Submit coverage data
          command: csmacnz.Coveralls.exe --useRelativePaths --multiple -i 'opencover=test/coverage.opencover.2.1.xml;opencover=test/coverage.opencover.3.0.xml' --serviceName circleci --jobId $env:CIRCLE_BUILD_NUM --commitId $(git rev-parse HEAD) --commitBranch $(git branch --show-current) --commitAuthor $(git log -1 --pretty=format:'%an') --commitEmail $(git log -1 --pretty=format:'%ae') --commitMessage $(git log -1 --pretty='%s')  --repoToken $env:COVERALLS_REPO_TOKEN
