### YamlMime:ManagedReference
apiRules:
- exclude:
      uidRegex: ^System\.Object$
      type: Type
- exclude:
      uidRegex: ^System\.Attribute$
      type: Type
- exclude:
      uidRegex: ^Dec\.Converter$
      type: Type
- exclude:
      uidRegex: ^Dec\.ConverterString$
      type: Type
- exclude:
      uidRegex: ^Dec\.ConverterRecord$
      type: Type
- exclude:
      uidRegex: ^Dec\.ConverterFactory$
      type: Type